@startuml OSU Companion

class Server {
    restaurantDatabase : Database
    clubDatabase : Database
    restaurantScraper : DiningScraper
    clubScraper : ClubScraper
    password : Database

    updateRestaurantDatabase()
    updateClubDatabase()
    AddUser()
    AuthenticateUser()
    DeleteUser()
}

Server *-- DiningScraper
Server *-- ClubScraper

class App {
    + tabList : Tab[]
    + restaurants : Restaurant[]
    + clubs : Club[]
    + studySpots : StudySpot[]
    + server : Server
    + user : User

    getRestuarants()
    getClubs()
    getStudySpots()
    loginUser()
    renderApp()
}

App *-- Server

class User {
    name : string
    email : string
    reviews : Review[]

    renderProfile()
}

class Restaurant {
    name : string
    rating : number
    times : string[]
    description : string
    menus : Menu[]
    building : string
    address : string
    reviews : Review[]

    getRestaurant()
}

class Club {
    name : string
    rating : number
    times : string[]
    description : string
    link : string
    reviews : Review[]

    getClubs()
}

class StudySpot {
    name : string
    rating : number
    times : string[]
    description : string
    building : string
    address : string
    reviews : Review[]

    getStudySpots()
}

App *-- Tab
App *-- User

class Tab {
    sortBy()
    filterBy()
    renderTab()
}

abstract class Card {
    + page : Page
    renderCard()
}

class DiningCard {
    + restaurant : Restaurant
}

class ClubCard {
    + club : Club
}

class StudyCard {
    + studySpot : StudySpot
}

DiningCard *-- Restaurant
ClubCard *-- Club
StudyCard *-- StudySpot

Restaurant *-- Review
Club *-- Review
StudySpot *-- Review

Card <|-- DiningCard
Card <|-- ClubCard
Card <|-- StudyCard

class Page {
    renderPage()
}

class Review {
    user: User
    time: DateTime
    imgs: Img[]
    description: string

    renderReview()
}

abstract class Scraper {
    server: Server
    data: list
    scrapeData()
    postToServer()
}

class DiningScraper {
    getRestuarantsInfo()
}

class ClubScraper {
    getClubsInfo()
}

Scraper <|-- DiningScraper
Scraper <|-- ClubScraper

App --> Tab
Tab ||--|{ Card
Card *-- Page

@enduml
